const DEFAULT={Push:[{name:'Incline Barbell Press',sets:4,reps:'8'},{name:'Machine Chest Press',sets:3,reps:'8'},{name:'Overhead Triceps Extension',sets:3,reps:'10'},{name:'Lateral Raises',sets:4,reps:'8'},{name:'Triceps Pushdown',sets:3,reps:'10'}],Pull:[{name:'Lat Pulldown',sets:4,reps:'8–12'},{name:'Machine Row',sets:3,reps:'12'},{name:'Lat Pullover',sets:3,reps:'12'},{name:'Reverse Pec Deck',sets:3,reps:'12'},{name:'Biceps Curl',sets:3,reps:'10'}],Legs:[{name:'Seated Hamstring Curl',sets:4,reps:'8'},{name:'Hack Squat',sets:4,reps:'8'},{name:'Leg Press',sets:4,reps:'8'},{name:'Calf Raises',sets:5,reps:'12'},{name:'Clarify exercise',sets:4,reps:'8'}]};
const KEY='dhwanit-fit-v3', OLD='dhwanit-fit-v2';
let data=load();let workout='Push',index=0,manageFilter='Push',progressFilter='all',restTimer=null;
function clone(x){return JSON.parse(JSON.stringify(x))} function today(){return new Date().toISOString().slice(0,10)}
function load(){try{let x=JSON.parse(localStorage.getItem(KEY)||'null');if(x)return normalize(x);let old=JSON.parse(localStorage.getItem(OLD)||'null');if(old)return normalize({...old,nutrition:{targets:{calories:2300,protein:85},entries:[],foods:[]}})}catch(e){}return normalize({exercises:clone(DEFAULT),logs:[],weights:[{date:today(),weight:44.1}],nutrition:{targets:{calories:2300,protein:85},entries:[],foods:[]},theme:'light'})}
function normalize(x){x.exercises=x.exercises||clone(DEFAULT);x.logs=x.logs||[];x.weights=x.weights||[];x.theme=x.theme||'light';x.nutrition=x.nutrition||{};x.nutrition.targets=x.nutrition.targets||{calories:2300,protein:85};x.nutrition.entries=x.nutrition.entries||[];x.nutrition.foods=x.nutrition.foods||[];return x}
function save(){localStorage.setItem(KEY,JSON.stringify(data))} function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))} function notify(m){let t=document.getElementById('toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}
function show(id){document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));document.getElementById(id).classList.add('active');document.querySelectorAll('.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.nav===id));if(id==='home')renderHome();if(id==='progress')renderProgress();if(id==='nutrition')renderNutrition();if(id==='body')renderBody();if(id==='manage')renderManage();scrollTo(0,0)}
function renderHome(){let w=data.weights.at(-1)?.weight||44.1;homeWeight.textContent=w.toFixed(1);['Push','Pull','Legs'].forEach(d=>document.getElementById(d.toLowerCase()+'Count').textContent=`${data.exercises[d].length} exercises`)}
function openWorkout(d){workout=d;index=0;workoutName.textContent=d;show('workout');renderExercise()}
function previous(name){return data.logs.filter(x=>x.exercise===name).at(-1)}
function renderExercise(){let ex=data.exercises[workout][index],prev=previous(ex.name),rows='';for(let i=0;i<ex.sets;i++)rows+=`<div class="set-row"><span>${i+1}</span><input id="wt${i}" type="number" step="0.5" placeholder="${prev?.weights?.[i]??'kg'}"><input id="rp${i}" type="number" placeholder="${prev?.reps?.[i]??ex.reps}"><button id="done${i}" onclick="doneSet(${i})">✓</button></div>`;workoutProgress.textContent=`${index+1}/${data.exercises[workout].length}`;workoutBar.style.width=`${index/data.exercises[workout].length*100}%`;exerciseView.innerHTML=`<div class="exercise-card"><div class="exercise-title"><div><h2>${esc(ex.name)}</h2><p>${ex.sets} sets · target ${esc(ex.reps)} reps</p></div><div class="set-adjust"><button onclick="changeWorkoutSets(-1)">− Set</button><b>${ex.sets}</b><button onclick="changeWorkoutSets(1)">+ Set</button></div></div>${prev?`<div class="previous"><b>Previous session · ${prev.date}</b><br>${prev.weights.map((w,i)=>`${w} kg × ${prev.reps[i]}`).join(' · ')}</div>`:`<div class="previous">No previous record. This will be your baseline.</div>`}<button class="secondary full" onclick="usePrevious()">↻ Use Previous Session</button><div class="set-head"><span>Set</span><span>Weight</span><span>Reps</span><span></span></div>${rows}<div id="rest" class="rest">Rest timer: ready</div><div class="controls"><button class="secondary" onclick="startRest()">Start 90s rest</button><button class="primary" onclick="saveExercise()">Save & Next</button></div></div>`}
function usePrevious(){let p=previous(data.exercises[workout][index].name);if(!p){notify('No previous session yet');return}p.weights.forEach((w,i)=>{let a=document.getElementById('wt'+i),b=document.getElementById('rp'+i);if(a)a.value=w;if(b)b.value=p.reps[i]});notify('Previous session filled — edit if needed')}
function changeWorkoutSets(delta){let ex=data.exercises[workout][index],n=Math.max(1,Math.min(10,ex.sets+delta));if(n===ex.sets)return;ex.sets=n;save();renderExercise()}
function doneSet(i){document.getElementById('done'+i).classList.toggle('done');if(document.getElementById('done'+i).classList.contains('done'))startRest()}
function startRest(seconds=90){clearInterval(restTimer);let left=seconds,el=document.getElementById('rest');if(!el)return;let tick=()=>{el.textContent=`Rest timer: ${String(Math.floor(left/60)).padStart(2,'0')}:${String(left%60).padStart(2,'0')}`;if(left<=0){clearInterval(restTimer);el.textContent='Rest complete'}left--};tick();restTimer=setInterval(tick,1000)}
function saveExercise(){let ex=data.exercises[workout][index],weights=[],reps=[];for(let i=0;i<ex.sets;i++){let w=Number(document.getElementById('wt'+i).value),r=Number(document.getElementById('rp'+i).value);if(!w||!r){notify('Enter weight and reps for every set');return}weights.push(w);reps.push(r)}data.logs.push({id:Date.now(),date:today(),workout,exercise:ex.name,weights,reps});save();if(index<data.exercises[workout].length-1){index++;renderExercise()}else{notify(`${workout} saved`);show('home')}}
function logsOnDate(d){return data.logs.filter(x=>x.date===d)}
function dayWorkoutStats(d){let ls=logsOnDate(d),vol=ls.reduce((s,l)=>s+l.weights.reduce((a,w,i)=>a+w*l.reps[i],0),0);return {logs:ls,volume:vol,sets:ls.reduce((s,l)=>s+l.weights.length,0)}}
function renderProgress(){let d=historyDate.value||today();historyDate.value=d;let s=dayWorkoutStats(d),nut=nutritionDay(d),bw=data.weights.filter(x=>x.date===d).at(-1)?.weight;daySummary.innerHTML=`<div class="summary-grid"><div class="stat-card"><span>WORKOUT</span><b>${s.logs.length?`${s.logs.length} exercises`:'Rest / no workout'}</b><small>${s.sets} sets · ${Math.round(s.volume).toLocaleString()} kg volume</small></div><div class="stat-card"><span>NUTRITION</span><b>${Math.round(nut.cal)} kcal</b><small>${nut.pro.toFixed(1)} g protein</small></div><div class="stat-card"><span>BODY WEIGHT</span><b>${bw?bw.toFixed(1):'—'} kg</b><small>${bw?'Logged on '+d:'No weight logged'}</small></div></div>`;let names=[...new Set(Object.values(data.exercises).flat().map(e=>e.name))].filter(n=>n!=='Clarify exercise');let list=names.filter(n=>progressFilter==='all'||data.exercises[progressFilter].some(e=>e.name===n));progressView.innerHTML=`<div class="card"><h3>Exercise details · ${d}</h3>${s.logs.length?s.logs.map(l=>`<div class="history-item"><b>${esc(l.exercise)}</b><span>${l.weights.map((w,i)=>`${w} kg × ${l.reps[i]}`).join(' · ')}</span></div>`).join(''):'<p class="hint">Nothing logged on this date.</p>'}</div><div class="card"><h3>Strength progress</h3>${list.map(n=>{let ls=data.logs.filter(x=>x.exercise===n),best=Math.max(0,...ls.flatMap(x=>x.weights));return `<div class="progress-row"><header><b>${esc(n)}</b><span>${best?best+' kg':'—'}</span></header><div class="last">${ls.length?`Last: ${ls.at(-1).date} · ${ls.at(-1).weights.map((w,i)=>`${w} × ${ls.at(-1).reps[i]}`).join(' · ')}`:'No record yet'}</div></div>`}).join('')}</div><div class="card"><h3>Charts</h3><canvas id="strengthChart" height="190"></canvas></div><div class="card"><h3>Calories by day</h3><canvas id="nutritionChart" height="190"></canvas></div><div class="card"><h3>Protein by day</h3><canvas id="proteinChart" height="190"></canvas></div>`;document.querySelectorAll('#progress .tab').forEach((b,i)=>b.classList.toggle('active',['all','Push','Pull','Legs'][i]===progressFilter));drawStrength();drawNutritionChart();drawProteinChart()}
function nutritionDay(d){let e=data.nutrition.entries.filter(x=>x.date===d);return {cal:e.reduce((s,x)=>s+x.calories,0),pro:e.reduce((s,x)=>s+x.protein,0)}}
function renderNutrition(){let d=nutritionDate.value||today();nutritionDate.value=d;let n=nutritionDay(d),t=data.nutrition.targets;nutritionSummary.innerHTML=`<div class="nutrition-card"><div><span>CALORIES</span><b>${Math.round(n.cal)}</b><small>/ ${t.calories} kcal</small></div><div><span>PROTEIN</span><b>${n.pro.toFixed(1)} g</b><small>/ ${t.protein} g</small></div></div><div class="goalbar"><i style="width:${Math.min(100,n.cal/t.calories*100)}%"></i></div>`;foodHistory.innerHTML=`<div class="card"><h3>Food log · ${d}</h3>${data.nutrition.entries.filter(x=>x.date===d).map(x=>`<div class="history-item"><div><b>${esc(x.name)}</b><small>${esc(x.serving||'')}</small></div><span>${Math.round(x.calories)} kcal · ${x.protein.toFixed(1)} g</span><button class="mini danger" onclick="deleteFood(${x.id})">×</button></div>`).join('')||'<p class="hint">No food logged yet.</p>'}</div><div class="card"><h3>Saved foods</h3>${data.nutrition.foods.map(f=>`<div class="history-item"><div><b>${esc(f.name)}</b><small>${esc(f.serving)}</small></div><span>${f.calories} kcal · ${f.protein} g</span><button class="mini" onclick="addSavedFood(${f.id})">Add</button></div>`).join('')||'<p class="hint">Save common foods from the add form after logging.</p>'}</div>`}
function addFoodEntry(){let name=foodName.value.trim(),cal=Number(foodCal.value),pro=Number(foodPro.value),serv=foodServing.value.trim();if(!name||cal<0||pro<0){notify('Enter food, calories and protein');return}let d=nutritionDate.value||today();data.nutrition.entries.push({id:Date.now(),date:d,name,calories:cal,protein:pro,serving:serv});if(!data.nutrition.foods.some(f=>f.name.toLowerCase()===name.toLowerCase()))data.nutrition.foods.push({id:Date.now()+1,name,calories:cal,protein:pro,serving:serv});save();foodName.value=foodCal.value=foodPro.value=foodServing.value='';renderNutrition();notify('Food added')}
function addSavedFood(id){let f=data.nutrition.foods.find(x=>x.id===id);if(!f)return;let d=nutritionDate.value||today();data.nutrition.entries.push({id:Date.now(),date:d,name:f.name,calories:f.calories,protein:f.protein,serving:f.serving});save();renderNutrition();notify('Added to food log')}
function deleteFood(id){data.nutrition.entries=data.nutrition.entries.filter(x=>x.id!==id);save();renderNutrition()}
function editTargets(){let t=data.nutrition.targets;document.getElementById('modalContent').innerHTML=`<h2>Nutrition targets</h2><div class="form"><label>Calories / day<input id="targetCal" type="number" value="${t.calories}"></label><label>Protein / day (g)<input id="targetPro" type="number" step="0.1" value="${t.protein}"></label><div class="modal-actions"><button class="secondary" onclick="closeModal()">Cancel</button><button class="primary" onclick="saveTargets()">Save</button></div></div>`;modal.classList.remove('hidden')}
function saveTargets(){data.nutrition.targets={calories:Number(targetCal.value)||2300,protein:Number(targetPro.value)||85};save();closeModal();renderNutrition();notify('Targets updated')}
function drawCanvas(id,series,labels,unit){let c=document.getElementById(id);if(!c)return;let dpr=devicePixelRatio||1,w=c.clientWidth||600,h=190;c.width=w*dpr;c.height=h*dpr;let x=c.getContext('2d');x.scale(dpr,dpr);x.clearRect(0,0,w,h);if(!series.length)return;x.font='12px system-ui';let pad=28,max=Math.max(...series,1),min=Math.min(...series);if(max===min)max=min+1;x.beginPath();series.forEach((v,i)=>{let px=pad+(w-pad*1.4)*(i/Math.max(1,series.length-1)),py=h-28-(h-55)*((v-min)/(max-min));i?x.lineTo(px,py):x.moveTo(px,py)});x.stroke();series.forEach((v,i)=>{let px=pad+(w-pad*1.4)*(i/Math.max(1,series.length-1)),py=h-28-(h-55)*((v-min)/(max-min));x.beginPath();x.arc(px,py,3,0,Math.PI*2);x.fill();if(i===series.length-1)x.fillText(`${Math.round(v)} ${unit}`,Math.min(px+7,w-90),py-8)});x.fillText(labels[0]||'',pad,h-8);x.fillText(labels.at(-1)||'',w-65,h-8)}
function lastDays(n=14){let a=[];for(let i=n-1;i>=0;i--){let d=new Date();d.setDate(d.getDate()-i);a.push(d.toISOString().slice(0,10))}return a}
function drawStrength(){let days=lastDays(14),vals=days.map(d=>{let l=data.logs.filter(x=>x.date===d);return l.length?Math.max(...l.flatMap(x=>x.weights)):0});drawCanvas('strengthChart',vals,days.map(d=>d.slice(5)),'kg')}
function drawNutritionChart(){let days=lastDays(14),vals=days.map(d=>nutritionDay(d).cal);drawCanvas('nutritionChart',vals,days.map(d=>d.slice(5)),'kcal')}
function drawProteinChart(){let days=lastDays(14),vals=days.map(d=>nutritionDay(d).pro);drawCanvas('proteinChart',vals,days.map(d=>d.slice(5)),'g')}
function renderBody(){let current=data.weights.at(-1)?.weight||44.1,goal=47,left=Math.max(0,goal-current);bodyCurrent.textContent=current.toFixed(1);homeWeight.textContent=current.toFixed(1);goalLeft.textContent=left.toFixed(1)+' kg left';goalBar.style.width=Math.min(100,Math.max(0,(current-44.1)/(goal-44.1)*100))+'%';bodyChart.innerHTML='<div class="card"><h3>Weight trend</h3><canvas id="weightChart" height="190"></canvas></div>';weightHistory.innerHTML=`<div class="card"><h3>Weight history</h3>${[...data.weights].reverse().slice(0,30).map(x=>`<div class="exercise-manage"><span>${x.date}</span><b>${x.weight.toFixed(1)} kg</b></div>`).join('')}</div>`;let days=lastDays(14);drawCanvas('weightChart',days.map(d=>{let x=data.weights.filter(w=>w.date===d);return x.at(-1)?.weight||null}).map((v,i,a)=>v??(a[i-1]??44.1)),days.map(d=>d.slice(5)),'kg')}
function saveWeight(){let w=Number(weightInput.value);if(!w)return;let d=today(),old=data.weights.find(x=>x.date===d);if(old)old.weight=w;else data.weights.push({date:d,weight:w});save();weightInput.value='';renderBody();renderHome();notify('Weight saved')}
function renderManage(){manageTabs.innerHTML=['Push','Pull','Legs'].map(x=>`<button class="tab ${manageFilter===x?'active':''}" onclick="manageFilter='${x}';renderManage()">${x}</button>`).join('');manageView.innerHTML=data.exercises[manageFilter].map((e,i)=>`<div class="exercise-manage"><div><b>${esc(e.name)}</b><small>${e.sets} sets · ${esc(e.reps)} reps</small></div><div class="manage-actions"><button class="mini" onclick="editExercise(${i})">Edit</button><button class="mini danger" onclick="removeExercise(${i})">Delete</button></div></div>`).join('')||'<div class="card"><p class="hint">No exercises here.</p></div>'}
function openAddModal(existing=null,i=-1){let e=existing||{name:'',sets:3,reps:'8–12'};modalContent.innerHTML=`<h2>${existing?'Edit exercise':'Add exercise'}</h2><div class="form"><label>Name<input id="mName" value="${esc(e.name)}"></label><label>Sets<input id="mSets" type="number" min="1" max="10" value="${e.sets}"></label><label>Target reps<input id="mReps" value="${esc(e.reps)}"></label><label>Workout<select id="mDay"><option>Push</option><option>Pull</option><option>Legs</option></select></label><div class="modal-actions"><button class="secondary" onclick="closeModal()">Cancel</button><button class="primary" onclick="saveExerciseConfig(${i},${existing?1:0})">Save</button></div></div>`;if(existing)mDay.value=manageFilter;modal.classList.remove('hidden')}
function closeModal(){modal.classList.add('hidden')}function saveExerciseConfig(i,editing){let name=mName.value.trim(),sets=Number(mSets.value),reps=mReps.value.trim(),day=mDay.value;if(!name||!sets||!reps){notify('Fill all fields');return}if(editing){let old=data.exercises[manageFilter].splice(i,1)[0];data.exercises[day].push({name,sets,reps});if(old.name!==name)data.logs=data.logs.map(l=>l.exercise===old.name?{...l,exercise:name}:l)}else data.exercises[day].push({name,sets,reps});save();closeModal();manageFilter=day;renderManage();renderHome();notify('Exercise saved')}
function editExercise(i){openAddModal(data.exercises[manageFilter][i],i)}function removeExercise(i){let e=data.exercises[manageFilter][i];if(confirm(`Remove "${e.name}"?`)){data.exercises[manageFilter].splice(i,1);save();renderManage();renderHome()}}
function setToday(){historyDate.value=today();renderProgress()}function setNutritionToday(){nutritionDate.value=today();renderNutrition()}
function exportData(){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download='dhwanit-fit-v3-backup.json';a.click()}
function importData(){let i=document.createElement('input');i.type='file';i.accept='.json';i.onchange=()=>{let f=i.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{try{data=normalize(JSON.parse(r.result));save();location.reload()}catch(e){notify('Invalid backup file')}};r.readAsText(f)};i.click()}
function resetHistory(){if(confirm('Clear workout and nutrition history?')){data.logs=[];data.nutrition.entries=[];save();renderProgress();renderNutrition();notify('History cleared')}}function resetEverything(){if(confirm('Reset all app data?')){localStorage.removeItem(KEY);localStorage.removeItem(OLD);location.reload()}}
themeBtn.onclick=()=>{data.theme=data.theme==='dark'?'light':'dark';document.body.classList.toggle('dark',data.theme==='dark');themeBtn.textContent=data.theme==='dark'?'☀':'☾';save()};dateText.textContent=new Date().toLocaleDateString(undefined,{weekday:'long',day:'numeric',month:'short',year:'numeric'});document.body.classList.toggle('dark',data.theme==='dark');themeBtn.textContent=data.theme==='dark'?'☀':'☾';historyDate.value=today();nutritionDate.value=today();renderHome();if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');
